name: sarri_ride
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2

  # Utility Packages
  http: ^1.4.0
  intl: ^0.20.2
  logger: ^2.5.0
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.2.1
  connectivity_plus: ^6.1.4
  lottie: ^3.3.1 # OR RIVE
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.0.15

  # State Management
  get: ^4.7.2
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2

  # Map and Location
  google_maps_flutter: ^2.10.0
  sliding_up_panel: ^2.0.0+1
  geolocator: ^13.0.2
  geocoding: ^4.0.0
  flutter_polyline_points: ^2.1.0
  google_places_flutter: ^2.0.9
  socket_io_client: ^3.1.2
  badges: ^3.1.2
  flutter_inappwebview: ^6.1.5
  share_plus: ^12.0.1
  flutter_image_compress: ^2.4.0
  flutter_svg: ^2.2.3
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.5.0
  flutter_webrtc: ^0.12.9
  permission_handler: ^12.0.1
  peerdart: ^0.5.6
  # flutter_inappwebview: ^5.8.0
flutter_inappwebview: ^6.0.0
share_plus: ^10.1.4

dependency_overrides:
  flutter_webrtc: ^0.12.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/content/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/
    - assets/icons/maps/

    #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
